#use llamafactory environment

In [1]:
from datasets import load_dataset
import pandas as pd
import json

/n/home07/than157/.conda/envs/llamafactory/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#load training set of hellaswag
dataset = load_dataset("allenai/winogrande", name="winogrande_xl", split="train")

#print dataset info
print("Dataset info:")
print(dataset)

print("# samples:", len(dataset)) #should be 39k
n_samples = len(dataset)

#convert to dataframe
df = dataset.to_pandas()
df.head()

Dataset info:
Dataset({
    features: ['sentence', 'option1', 'option2', 'answer'],
    num_rows: 40398
})
# samples: 40398

                                            sentence option1 option2 answer
0  Ian volunteered to eat Dennis's menudo after a...     Ian  Dennis      2
1  Ian volunteered to eat Dennis's menudo after a...     Ian  Dennis      1
2  He never comes to my home, but I always go to ...    home   house      1
3  He never comes to my home, but I always go to ...    home   house      2
4  Kyle doesn't wear leg warmers to bed, while Lo...    Kyle   Logan      2

In [3]:
# add 'correct_word' using Winogrande's answer key:
# answer == '1' -> option1, answer == '2' -> option2
df["correct_word"] = df.apply(
    lambda row: row["option1"] if str(row["answer"]) == "1" else row["option2"],
    axis=1,
)
df.head(50)

,sentence,option1,option2,answer,correct_word
0,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,2,Dennis
1,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,1,Ian
2,"He never comes to my home, but I always go to ...",home,house,1,home
3,"He never comes to my home, but I always go to ...",home,house,2,house
4,"Kyle doesn't wear leg warmers to bed, while Lo...",Kyle,Logan,2,Logan
5,"Kyle doesn't wear leg warmers to bed, while Lo...",Kyle,Logan,1,Kyle
6,The GPS and map helped me navigate home. I go...,GPS,map,2,map
7,The GPS and map helped me navigate home. I go...,GPS,map,1,GPS
8,Emily looked up and saw Patricia racing by ove...,Emily,Patricia,2,Patricia
9,Emily looked up and saw Patricia racing by ove...,Emily,Patricia,1,Emily
10,The treasury workers took the gold bars off of...,safe,trolley,2,trolley
11,The treasury workers took the gold bars off of...,safe,trolley,1,safe
12,He thought he had time to take the scenic rout...,route,store,1,route
13,He thought he had time to take the scenic rout...,route,store,2,store
14,She remembered how annoying it is to dust her ...,chair,table,2,table
15,She remembered how annoying it is to dust her ...,chair,table,1,chair
16,"To overcome behavioural bias, we need to focus...",unconscious,conscious,2,conscious
17,"To overcome behavioural bias, we need to focus...",unconscious,conscious,1,unconscious
18,Megan has a lot less money than Jessica becaus...,Megan,Jessica,2,Jessica
19,Megan has a lot more money than Jessica becaus...,Megan,Jessica,1,Megan
20,I picked up a bag of peanuts and raisins for a...,raisins,peanuts,2,peanuts
21,I picked up a bag of peanuts and raisins for a...,raisins,peanuts,1,raisins
22,Craig really loves to clean all the time but D...,Craig,Derrick,1,Craig
23,Craig really loves to clean all the time but D...,Craig,Derrick,2,Derrick
24,Dennis gave his hammer to Robert so he could h...,Dennis,Robert,1,Dennis
25,Dennis gave his hammer to Robert so he could h...,Dennis,Robert,2,Robert
26,The party was more interesting and uplifing th...,party,funeral,2,funeral
27,The party was more interesting and uplifting t...,party,funeral,1,party
28,The geese prefer to nest in the fields rather ...,fields,forests,2,forests
29,The geese prefer to nest in the fields rather ...,fields,forests,1,fields
30,"The plant took up too much room in the urn, be...",plant,urn,2,urn
31,"The plant took up too much room in the urn, be...",plant,urn,1,plant
32,I installed a new bird house outside above the...,bird house,ground,1,bird house
33,I installed a new bird house outside above the...,bird house,ground,2,ground
34,I prefer spa to the pool and I find the cold w...,spa,pool,2,pool
35,I prefer spa to the pool and I find the hot wa...,spa,pool,1,spa
36,Megan said it would be liberating to go out wi...,Megan,Elena,2,Elena
37,Megan said it would be liberating to go out wi...,Megan,Elena,1,Megan
38,Donald was richer than Leslie was because comp...,Donald,Leslie,1,Donald
39,Donald was poorer than Leslie was because comp...,Donald,Leslie,2,Leslie
40,"Feeling a draft, William asked Neil to please ...",William,Neil,2,Neil
41,"Feeling a draft, William asked Neil to please ...",William,Neil,1,William
42,Lindsey loved the taste of duck but Megan like...,Lindsey,Megan,2,Megan
43,Lindsey loved the taste of duck but Megan like...,Lindsey,Megan,1,Lindsey
44,Elena would grab their inventory in the back o...,Elena,Megan,2,Megan
45,Elena would grab their inventory in the back o...,Elena,Megan,1,Elena
46,Kenneth asked Dennis what time the dance was b...,Kenneth,Dennis,2,Dennis
47,Kenneth asked Dennis what time the dance was b...,Kenneth,Dennis,1,Kenneth
48,Eric was teaching all of the proper stretches ...,Eric,Neil,1,Eric
49,Eric was teaching all of the proper stretches ...,Eric,Neil,2,Neil

In [4]:
#create 'sentence_prefix' and 'sentence_suffix' columns
df["sentence_prefix"] = df["sentence"].str.split("_").str[0]
df["sentence_suffix"] = df["sentence"].str.split("_").str[1]

#remove whitespace from 'sentence_prefix' and 'sentence_suffix'
df["sentence_prefix"] = df["sentence_prefix"].str.rstrip() #remove trailing space
df["sentence_suffix"] = df["sentence_suffix"].str.lstrip() #remove leading space

df.head()

,sentence,option1,option2,answer,correct_word,sentence_prefix,sentence_suffix
0,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,2,Dennis,Ian volunteered to eat Dennis's menudo after a...,despised eating intestine.
1,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,1,Ian,Ian volunteered to eat Dennis's menudo after a...,enjoyed eating intestine.
2,"He never comes to my home, but I always go to ...",home,house,1,home,"He never comes to my home, but I always go to ...",is smaller.
3,"He never comes to my home, but I always go to ...",home,house,2,house,"He never comes to my home, but I always go to ...",is bigger.
4,"Kyle doesn't wear leg warmers to bed, while Lo...",Kyle,Logan,2,Logan,"Kyle doesn't wear leg warmers to bed, while Lo...",is more likely to live in a colder climate.

In [5]:
#print first 50 rows, showing the full contents of each column -- check that the data is correct
print(df.head(50).to_string())

                                                                                                                                                           sentence      option1    option2 answer correct_word                                                                                                                       sentence_prefix                              sentence_suffix
0                                                           Ian volunteered to eat Dennis's menudo after already having a bowl because _ despised eating intestine.          Ian     Dennis      2       Dennis                                                            Ian volunteered to eat Dennis's menudo after already having a bowl because                   despised eating intestine.
1                                                            Ian volunteered to eat Dennis's menudo after already having a bowl because _ enjoyed eating intestine.          Ian     Dennis      1          Ian                                                            Ian volunteered to eat Dennis's menudo after already having a bowl because                    enjoyed eating intestine.
2                                                                                 He never comes to my home, but I always go to his house because the _ is smaller.         home      house      1         home                                                                   He never comes to my home, but I always go to his house because the                                  is smaller.
3                                                                                  He never comes to my home, but I always go to his house because the _ is bigger.         home      house      2        house                                                                   He never comes to my home, but I always go to his house because the                                   is bigger.
4                                               Kyle doesn't wear leg warmers to bed, while Logan almost always does. _ is more likely to live in a colder climate.         Kyle      Logan      2        Logan                                                                 Kyle doesn't wear leg warmers to bed, while Logan almost always does.  is more likely to live in a colder climate.
5                                               Kyle doesn't wear leg warmers to bed, while Logan almost always does. _ is more likely to live in a warmer climate.         Kyle      Logan      1         Kyle                                                                 Kyle doesn't wear leg warmers to bed, while Logan almost always does.  is more likely to live in a warmer climate.
6                                                                           The GPS and map helped me navigate home.  I got lost when the _ got turned upside down.          GPS        map      2          map                                                                         The GPS and map helped me navigate home.  I got lost when the                      got turned upside down.
7                                                                                   The GPS and map helped me navigate home.  I got lost when the _ got turned off.          GPS        map      1          GPS                                                                         The GPS and map helped me navigate home.  I got lost when the                              got turned off.
8                                                                                       Emily looked up and saw Patricia racing by overhead, as _ was on the ramp .        Emily   Patricia      2     Patricia                                                                               Emily looked up and saw Patricia racing by overhead, as                            was on the ramp .
9                                                                                    Emily looked up and saw Patricia racing by overhead, as _ was under the ramp .        Emily   Patricia      1        Emily                                                                               Emily looked up and saw Patricia racing by overhead, as                         was under the ramp .
10                                                   The treasury workers took the gold bars off of the trolley and stacked them in the safe until the _ was empty.         safe    trolley      2      trolley                                     The treasury workers took the gold bars off of the trolley and stacked them in the safe until the                                   was empty.
11                                                    The treasury workers took the gold bars off of the trolley and stacked them in the safe until the _ was full.         safe    trolley      1         safe                                     The treasury workers took the gold bars off of the trolley and stacked them in the safe until the                                    was full.
12                                                                  He thought he had time to take the scenic route to the store, but the _ was under construction.        route      store      1        route                                                                 He thought he had time to take the scenic route to the store, but the                      was under construction.
13                                                                        He thought he had time to take the scenic route to the store, but the _ was closed early.        route      store      2        store                                                                 He thought he had time to take the scenic route to the store, but the                            was closed early.
14                                        She remembered how annoying it is to dust her wood chair so she bought a plastic table instead.  Cleaning the _ is quick.        chair      table      2        table                         She remembered how annoying it is to dust her wood chair so she bought a plastic table instead.  Cleaning the                                    is quick.
15                               She remembered how annoying it is to dust her wood chair so she bought a plastic table instead.  Cleaning the _ is time consuming.        chair      table      1        chair                         She remembered how annoying it is to dust her wood chair so she bought a plastic table instead.  Cleaning the                           is time consuming.
16    To overcome behavioural bias, we need to focus more on changing the conscious actions instead of the unconscious actions because the _ actions are voluntary.  unconscious  conscious      2    conscious  To overcome behavioural bias, we need to focus more on changing the conscious actions instead of the unconscious actions because the                       actions are voluntary.
17  To overcome behavioural bias, we need to focus more on changing the conscious actions instead of the unconscious actions because the _ actions are involuntary.  unconscious  conscious      1  unconscious  To overcome behavioural bias, we need to focus more on changing the conscious actions instead of the unconscious actions because the                     actions are involuntary.
18                                                                        Megan has a lot less money than Jessica because _ just bought the winning lottery ticket.        Megan    Jessica      2      Jessica                                                                                       Megan has a lot less money than Jessica because      just bought the winning lottery ticket.
19                                                                        Megan has a lot more money than Jessica because _ just bought the winning lottery ticket.        Megan    Jessica      1        Megan                                                                                       Megan has a lot more money than Jessica because      just bought the winning lottery ticket.
20                                                    I picked up a bag of peanuts and raisins for a snack. I wanted a sweeter snack out so I stored the _ for now.      raisins    peanuts      2      peanuts                                    I picked up a bag of peanuts and raisins for a snack. I wanted a sweeter snack out so I stored the                                     for now.
21                                                       I picked up a bag of peanuts and raisins for a snack. I wanted a sweeter snack out so I ate the _ for now.      raisins    peanuts      1      raisins                                       I picked up a bag of peanuts and raisins for a snack. I wanted a sweeter snack out so I ate the                                     for now.
22                                                                            Craig really loves to clean all the time but Derrick does not because _ is very neat.        Craig    Derrick      1        Craig                                                                 Craig really loves to clean all the time but Derrick does not because                                is very neat.
23                                                                          Craig really loves to clean all the time but Derrick does not because _ is very untidy.        Craig    Derrick      2      Derrick                                                                 Craig really loves to clean all the time but Derrick does not because                              is very untidy.
24                                                                          Dennis gave his hammer to Robert so he could hammer the nails. _ had plenty of hammers.       Dennis     Robert      1       Dennis                                                                        Dennis gave his hammer to Robert so he could hammer the nails.                       had plenty of hammers.
25                                                                                 Dennis gave his hammer to Robert so he could hammer the nails. _ had no hammers.       Dennis     Robert      2       Robert                                                                        Dennis gave his hammer to Robert so he could hammer the nails.                              had no hammers.
26                                                                            The party was more interesting and uplifing than the funeral because the _ was rigid.        party    funeral      2      funeral                                                              The party was more interesting and uplifing than the funeral because the                                   was rigid.
27                                                                        The party was more interesting and uplifting than the funeral because the _ was flexible.        party    funeral      1        party                                                             The party was more interesting and uplifting than the funeral because the                                was flexible.
28                                                       The geese prefer to nest in the fields rather than the forests because in the _ predators are more hidden.       fields    forests      2      forests                                                         The geese prefer to nest in the fields rather than the forests because in the                   predators are more hidden.
29                                                      The geese prefer to nest in the fields rather than the forests because in the _ predators are very visible.       fields    forests      1       fields                                                         The geese prefer to nest in the fields rather than the forests because in the                  predators are very visible.
30                                                                                             The plant took up too much room in the urn, because the _ was small.        plant        urn      2          urn                                                                               The plant took up too much room in the urn, because the                                   was small.
31                                                                                             The plant took up too much room in the urn, because the _ was large.        plant        urn      1        plant                                                                               The plant took up too much room in the urn, because the                                   was large.
32                                    I installed a new bird house outside above the ground, but had to prop it up higher away from my cat since the _ was too low.   bird house     ground      1   bird house                        I installed a new bird house outside above the ground, but had to prop it up higher away from my cat since the                                 was too low.
33                                   I installed a new bird house outside above the ground, but had to prop it up higher away from my cat since the _ was too high.   bird house     ground      2       ground                        I installed a new bird house outside above the ground, but had to prop it up higher away from my cat since the                                was too high.
34                                                                 I prefer spa to the pool and I find the cold water in the _  not relaxing at the end of the day.          spa       pool      2         pool                                                                             I prefer spa to the pool and I find the cold water in the          not relaxing at the end of the day.
35                                                                       I prefer spa to the pool and I find the hot water in the _ relaxing at the end of the day.          spa       pool      1          spa                                                                              I prefer spa to the pool and I find the hot water in the              relaxing at the end of the day.
36                                         Megan said it would be liberating to go out without makeup like Elena does. _ never wore makeup when she left the house.        Megan      Elena      2        Elena                                                           Megan said it would be liberating to go out without makeup like Elena does.   never wore makeup when she left the house.
37                                        Megan said it would be liberating to go out without makeup like Elena does. _ always wore makeup when she left the house.        Megan      Elena      1        Megan                                                           Megan said it would be liberating to go out without makeup like Elena does.  always wore makeup when she left the house.
38                                                                         Donald was richer than Leslie was because companies had found oil on the property of _ .       Donald     Leslie      1       Donald                                                  Donald was richer than Leslie was because companies had found oil on the property of                                            .
39                                                                         Donald was poorer than Leslie was because companies had found oil on the property of _ .       Donald     Leslie      2       Leslie                                                  Donald was poorer than Leslie was because companies had found oil on the property of                                            .
40                                                                         Feeling a draft, William asked Neil to please close the front door because _ was closer.      William       Neil      2         Neil                                                            Feeling a draft, William asked Neil to please close the front door because                                  was closer.
41                                                                   Feeling a draft, William asked Neil to please close the front door because _ was farther away.      William       Neil      1      William                                                            Feeling a draft, William asked Neil to please close the front door because                            was farther away.
42                                                       Lindsey loved the taste of duck but Megan liked chicken better. _ ordered the kung pao chicken for dinner.      Lindsey      Megan      2        Megan                                                                       Lindsey loved the taste of duck but Megan liked chicken better.     ordered the kung pao chicken for dinner.
43                                                            Lindsey loved the taste of duck but Megan liked chicken better. _ ordered the Peking Duck for dinner.      Lindsey      Megan      1      Lindsey                                                                       Lindsey loved the taste of duck but Megan liked chicken better.          ordered the Peking Duck for dinner.
44                                            Elena would grab their inventory in the back of the store for Megan to sell each time because _ was a loyal customer.        Elena      Megan      2        Megan                                         Elena would grab their inventory in the back of the store for Megan to sell each time because                        was a loyal customer.
45                                            Elena would grab their inventory in the back of the store for Megan to sell each time because _ was a businessperson.        Elena      Megan      1        Elena                                         Elena would grab their inventory in the back of the store for Megan to sell each time because                        was a businessperson.
46                                                                                    Kenneth asked Dennis what time the dance was being held, but _ had forgotten.      Kenneth     Dennis      2       Dennis                                                                          Kenneth asked Dennis what time the dance was being held, but                               had forgotten.
47                                                                                Kenneth asked Dennis what time the dance was being held, because _ had forgotten.      Kenneth     Dennis      1      Kenneth                                                                      Kenneth asked Dennis what time the dance was being held, because                               had forgotten.
48                                                                     Eric was teaching all of the proper stretches to Neil, because _ was using them to get paid.         Eric       Neil      1         Eric                                                                        Eric was teaching all of the proper stretches to Neil, because                  was using them to get paid.
49                                                                 Eric was teaching all of the proper stretches to Neil, because _ was using them to get in shape.         Eric       Neil      2         Neil                                                                        Eric was teaching all of the proper stretches to Neil, because              was using them to get in shape.

In [6]:
#shuffle rows since rows are in pairs
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

,sentence,option1,option2,answer,correct_word,sentence_prefix,sentence_suffix
0,Monica confided in Cynthia that she had prepar...,Monica,Cynthia,2,Cynthia,Monica confided in Cynthia that she had prepar...,was impressed.
1,Rebecca had less grass in their yard than Elen...,Rebecca,Elena,1,Rebecca,Rebecca had less grass in their yard than Elen...,had more rabbits in their yard.
2,Erin has a lot of dry skin on their arms and l...,Erin,Angela,2,Angela,Erin has a lot of dry skin on their arms and l...,has been using lotion to keep their skin soft.
3,Joel really enjoyed shopping and Hunter did no...,Joel,Hunter,1,Joel,Joel really enjoyed shopping and Hunter did no...,intended to be a personal shopper.
4,The spouse of Logan cheated on him with Brett ...,Logan,Brett,1,Logan,The spouse of Logan cheated on him with Brett ...,always ignored her feelings.

In [7]:
### create json file

#format data for sft
data = []

for idx, row in df.iterrows():
    item = {
        "instruction": f'{row["sentence_prefix"]} {row["correct_word"]}',
        "input": "",
        "output": row["sentence_suffix"]
    }
    data.append(item)
    #track progress
    if idx % 10000 == 0:
        print(f"Processed {idx} rows")
    if idx == (n_samples - 1):
        print(f"Processed {idx} rows (last row)")

#save to JSON file
with open("data/winogrande.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("Complete!")

Processed 0 rows
Processed 10000 rows
Processed 20000 rows
Processed 30000 rows
Processed 40000 rows
Processed 40397 rows (last row)
Complete!